// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlsluozubnwgtwlglwep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsc2x1b3p1Ym53Z3R3bGdsd2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDQ5NzEsImV4cCI6MjA2MzkyMDk3MX0.AsnnMtyyuUlWmdrrmKXVcqH3ZQD80wlY0ZGFG30Fng0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);